name: Build and deploy ASP.Net Core app to Azure Web App - Gotorz20250514095933
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore dependencies
        run: dotnet restore Gotorz.sln
        
      - name: Build with dotnet
        run: dotnet build Gotorz.sln --configuration Release --no-restore
        
      - name: List directory structure before publish
        run: find . -type f -name "*.csproj" | sort
        
      - name: Publish Server Project
        run: dotnet publish Gotorz/Gotorz/Gotorz.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp
        
      - name: List output directory structure
        run: find ${{env.DOTNET_ROOT}}/myapp -type f | grep -v ".dll" | sort
        
      - name: Check for web.config
        run: cat ${{env.DOTNET_ROOT}}/myapp/web.config || echo "web.config not found!"
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          
      - name: List files to be deployed
        run: find . -type f | grep -v ".dll" | sort
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_32A648A5DB6348958D4C6A3F81A973F9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9761B4AD937C4133BD539B18EFD586A6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F38C5E8DE28D45EE8FA85ED065D6F1A0 }}
          
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Gotorz20250514095933'
          slot-name: 'Production'
          package: .
