name: Build and deploy ASP.Net Core app to Azure Web App - Gotorz20250514095933

on:

  push:
    branches:
      - master
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
 
    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4

        with:

          dotnet-version: '8.0'
 
      - name: Restore dependencies

        run: dotnet restore Gotorz/Gotorz.csproj
 
      - name: Build with dotnet

        run: dotnet build Gotorz/Gotorz.csproj --configuration Release
 
      - name: dotnet publish

        run: dotnet publish Gotorz/Gotorz.csproj -c Release -o ./publish --no-cache
 
      - name: Upload artifact for deployment job

        uses: actions/upload-artifact@v4

        with:

          name: .net-app

          path: ./publish
 
  deploy:

    runs-on: ubuntu-latest

    needs: build

    environment:

      name: 'Production'

      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    permissions:

      id-token: write

      contents: read
 
    steps:

      - name: Download artifact from build job

        uses: actions/download-artifact@v4

        with:

          name: .net-app

      - name: Login to Azure

        uses: azure/login@v2

        with:

          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_32A648A5DB6348958D4C6A3F81A973F9 }}

          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9761B4AD937C4133BD539B18EFD586A6 }}

          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F38C5E8DE28D45EE8FA85ED065D6F1A0 }}
 
      - name: Deploy to Azure Web App

        id: deploy-to-webapp

        uses: azure/webapps-deploy@v3

        with:

          app-name: 'Gotorz20250514095933'

          slot-name: 'Production'

          package: ./publish
 
name: Build and deploy ASP.Net Core app to Azure Web App - Gotorz20250514095933
 
on:

  push:

    branches:

      - master

  workflow_dispatch:
 
jobs:

  build:

    runs-on: ubuntu-latest

    permissions:

      contents: read
 
    steps:

      - uses: actions/checkout@v4
 
      - name: Set up .NET Core

        uses: actions/setup-dotnet@v4

        with:

          dotnet-version: '8.0'
 
      - name: Restore dependencies

        run: dotnet restore Gotorz.csproj
 
      - name: Build with dotnet

        run: dotnet build Gotorz.csproj --configuration Release
 
      - name: dotnet publish

        run: dotnet publish Gotorz.csproj -c Release -o ./publish --no-cache
 
      - name: Upload artifact for deployment job

        uses: actions/upload-artifact@v4

        with:

          name: .net-app

          path: ./publish
 
  deploy:

    runs-on: ubuntu-latest

    needs: build

    environment:

      name: 'Production'

      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    permissions:

      id-token: write

      contents: read
 
    steps:

      - name: Download artifact from build job

        uses: actions/download-artifact@v4

        with:

          name: .net-app

      - name: Login to Azure

        uses: azure/login@v2

        with:

          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_32A648A5DB6348958D4C6A3F81A973F9 }}

          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9761B4AD937C4133BD539B18EFD586A6 }}

          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F38C5E8DE28D45EE8FA85ED065D6F1A0 }}
 
      - name: Deploy to Azure Web App

        id: deploy-to-webapp

        uses: azure/webapps-deploy@v3

        with:

          app-name: 'Gotorz20250514095933'

          slot-name: 'Production'

          package: ./publish

 
